/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package SystemGUI.Impuesto;

import javax.swing.JOptionPane;

import controlimpuestos.cImpuestos;
import controlimpuestos.SystemCRUD.crudImpuestos;

/**
 *
 * @author fanta
 */
public class frmImpuestoBuscar extends javax.swing.JPanel {

    //Variables requeridas para obtener los datos del formulario
    private String descripcion, tasaImpuesto, 
    fechaVencimiento, idImpuesto, idAnterior;

    //Instancia del objeto SystemCRUD.crudImpuestos
    private crudImpuestos crudImpuestos;

    public static cImpuestos impuestoResultado;

    private java.awt.Color lightGray = new java.awt.Color(153,153,153);


    /**
     * Creates new form frmTest
     */
    public frmImpuestoBuscar() {
        initComponents();

        //Instanciar la clase crudImpuestos
        crudImpuestos = new crudImpuestos();

        pnlBuscar.setVisible(true);
        pnlResultado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBuscar = new javax.swing.JPanel();
        h1Busqueda = new javax.swing.JLabel();
        jlFecha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tfFecha = new javax.swing.JTextField();
        jlID = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        tfID = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JPanel();
        jlBuscar = new javax.swing.JLabel();
        pnlResultado = new javax.swing.JPanel();
        h1Registro = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        jlEliminar = new javax.swing.JLabel();
        btnEditar = new javax.swing.JPanel();
        jlEditar = new javax.swing.JLabel();
        jlTasa = new javax.swing.JLabel();
        tfTasaResultado = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jlFecha1 = new javax.swing.JLabel();
        tfFechaResultado = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        taDescripcionResultado = new javax.swing.JTextArea();
        jlDescripcion = new javax.swing.JLabel();
        jlcharWarning = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        pnlBuscar.setBackground(new java.awt.Color(255, 255, 255));
        pnlBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        h1Busqueda.setBackground(new java.awt.Color(21, 14, 48));
        h1Busqueda.setFont(new java.awt.Font("Roboto", 3, 22)); // NOI18N
        h1Busqueda.setText("Búsqueda de impuestos");
        pnlBuscar.add(h1Busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 26, 268, 40));

        jlFecha.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jlFecha.setForeground(new java.awt.Color(21, 14, 48));
        jlFecha.setText("Por Fecha de Vencimiento:");
        pnlBuscar.add(jlFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 106, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(21, 14, 48));
        pnlBuscar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 230, 10));

        tfFecha.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        tfFecha.setForeground(new java.awt.Color(153, 153, 153));
        tfFecha.setText("Ingrese la fecha de vencimiento");
        tfFecha.setBorder(null);
        tfFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFechaFocusGained(evt);
            }
        });
        pnlBuscar.add(tfFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 230, 30));

        jlID.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jlID.setForeground(new java.awt.Color(21, 14, 48));
        jlID.setText("Por ID:");
        pnlBuscar.add(jlID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(21, 14, 48));
        pnlBuscar.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 80, 10));

        tfID.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        tfID.setForeground(new java.awt.Color(153, 153, 153));
        tfID.setText("Ingrese el ID");
        tfID.setBorder(null);
        tfID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfIDFocusGained(evt);
            }
        });
        pnlBuscar.add(tfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 80, 30));

        btnBuscar.setBackground(new java.awt.Color(21, 14, 48));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlBuscar.setBackground(new java.awt.Color(21, 14, 48));
        jlBuscar.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jlBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jlBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemGUI/images/searchMini.png"))); // NOI18N
        jlBuscar.setText("Buscar");
        jlBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlBuscar.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 494, -1, -1));

        add(pnlBuscar, "card2");

        pnlResultado.setBackground(new java.awt.Color(255, 255, 255));
        pnlResultado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        h1Registro.setBackground(new java.awt.Color(21, 14, 48));
        h1Registro.setFont(new java.awt.Font("Roboto", 3, 22)); // NOI18N
        h1Registro.setText("Resultado de la búsqueda");
        pnlResultado.add(h1Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, 40));

        btnEliminar.setBackground(new java.awt.Color(255, 51, 51));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlEliminar.setBackground(new java.awt.Color(21, 14, 48));
        jlEliminar.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jlEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jlEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemGUI/images/deleteMini.png"))); // NOI18N
        jlEliminar.setText("Eliminar");
        jlEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlEliminarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlResultado.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, -1, -1));

        btnEditar.setBackground(new java.awt.Color(21, 14, 48));
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlEditar.setBackground(new java.awt.Color(21, 14, 48));
        jlEditar.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jlEditar.setForeground(new java.awt.Color(255, 255, 255));
        jlEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SystemGUI/images/editMini.png"))); // NOI18N
        jlEditar.setText("Editar");
        jlEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlEditarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnEditarLayout = new javax.swing.GroupLayout(btnEditar);
        btnEditar.setLayout(btnEditarLayout);
        btnEditarLayout.setHorizontalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnEditarLayout.setVerticalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlResultado.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, -1, -1));

        jlTasa.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jlTasa.setForeground(new java.awt.Color(21, 14, 48));
        jlTasa.setText("Tasa del impuesto:");
        pnlResultado.add(jlTasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        tfTasaResultado.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        tfTasaResultado.setForeground(new java.awt.Color(153, 153, 153));
        tfTasaResultado.setBorder(null);
        tfTasaResultado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTasaResultadoFocusGained(evt);
            }
        });
        pnlResultado.add(tfTasaResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 230, 30));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(21, 14, 48));
        pnlResultado.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 230, 10));

        jlFecha1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jlFecha1.setForeground(new java.awt.Color(21, 14, 48));
        jlFecha1.setText("Fecha de Vencimiento:");
        pnlResultado.add(jlFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        tfFechaResultado.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        tfFechaResultado.setForeground(new java.awt.Color(153, 153, 153));
        tfFechaResultado.setBorder(null);
        tfFechaResultado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFechaResultadoFocusGained(evt);
            }
        });
        pnlResultado.add(tfFechaResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 230, 30));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(21, 14, 48));
        pnlResultado.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 230, 10));

        taDescripcionResultado.setColumns(20);
        taDescripcionResultado.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        taDescripcionResultado.setForeground(new java.awt.Color(21, 14, 48));
        taDescripcionResultado.setRows(5);
        taDescripcionResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pnlResultado.add(taDescripcionResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 590, -1));

        jlDescripcion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jlDescripcion.setForeground(new java.awt.Color(21, 14, 48));
        jlDescripcion.setText("Descripción:");
        pnlResultado.add(jlDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jlcharWarning.setFont(new java.awt.Font("Roboto Light", 2, 12)); // NOI18N
        jlcharWarning.setForeground(new java.awt.Color(21, 14, 48));
        jlcharWarning.setText("Max 100 caracteres.");
        pnlResultado.add(jlcharWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        add(pnlResultado, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void jlEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEditarMouseClicked
        //Guardar ID anterior para la busqueda en DB
        idAnterior = String.valueOf(crudImpuestos.returnIdAnterior());

        //Obtener los datos del formulario
        descripcion = taDescripcionResultado.getText();
        tasaImpuesto = tfTasaResultado.getText();
        fechaVencimiento = tfFechaResultado.getText();
        //Verificar que los campos no esten vacios
        if (!descripcion.equals("") || !tasaImpuesto.equals("") || !fechaVencimiento.equals("")) {
            try {
                //Actualizar los datos del objeto impuesto previamente encontrado
                impuestoResultado.setDescripcion(descripcion);;
                impuestoResultado.setTasaImpuesto(Double.parseDouble(tasaImpuesto));
                impuestoResultado.setFecha(fechaVencimiento);

                //Llamar al metodo de actualizar
                crudImpuestos.actualizarImpuesto(impuestoResultado, idAnterior);

                //Mostrar mensaje de exito
                JOptionPane.showMessageDialog(null, "Impuesto actualizado con éxito", "Exito", JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error en el proceso de actualización: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jlEditarMouseClicked

    private void jlEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlEliminarMousePressed
        //Obtener el ID del impuesto a eliminar
        idAnterior = String.valueOf(crudImpuestos.returnIdAnterior());

        //Confirmar que se desea eliminar el impuesto
        int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea eliminar el impuesto?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        try {
            //Eliminar el cliente en caso de seleccionar confirmar
            if (opcion == JOptionPane.YES_OPTION) {
                //Se invoca el metodo de eliminarCliente
                crudImpuestos.eliminarImpuesto(impuestoResultado);

                //Evitar que se seleccione el campo "Por Fecha:" por defecto al volver al panel de busqueda
                h1Busqueda.requestFocusInWindow();

                //Volver a la pantalla de busqueda
                pnlResultado.setVisible(false);
                pnlBuscar.setVisible(true);


            } else {
                JOptionPane.showMessageDialog(null, "Se ha cancelado el proceso de eliminación", "Eliminación cancelada", JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en el proceso de eliminación: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jlEliminarMousePressed

    private void jlBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBuscarMouseClicked
        //Obtener el texto de los campos
        fechaVencimiento = tfFecha.getText();
        idImpuesto = tfID.getText();

        //Buscar y mostrar los datos segun el campo llenado
        if (!fechaVencimiento.equals("") && !fechaVencimiento.equals("Ingrese la fecha de vencimiento")) {

            //Llamar al metodo de busqueda y guardar los resultados
            try {
                impuestoResultado = crudImpuestos.buscarImpuestoFecha(fechaVencimiento);

                h1Busqueda.requestFocusInWindow();
                tfFecha.setText("Ingrese el nombre");
                tfFecha.setForeground(lightGray);
                tfID.setText("Ingrese el ID");
                tfID.setForeground(lightGray);

                //Verificar que el cliente exista y mostrar los datos en el nuevo panel
                if (impuestoResultado != null) {
                    taDescripcionResultado.setText(impuestoResultado.getDescripcion());
                    tfTasaResultado.setText(String.valueOf(impuestoResultado.getTasaImpuesto()));
                    tfFechaResultado.setText(impuestoResultado.getFecha());

                    //Cambiar de panel
                    pnlBuscar.setVisible(false);
                    pnlResultado.setVisible(true);

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error en el proceso de busqueda: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else if (!idImpuesto.equals("") && !idImpuesto.equals("Ingrese el ID")) {

            //Llamar al metodo de busqueda y guardar los resultados
            try {
                impuestoResultado = crudImpuestos.buscarImpuestoID(idImpuesto);

                h1Busqueda.requestFocusInWindow();
                tfFecha.setText("Ingrese el nombre");
                tfFecha.setForeground(lightGray);
                tfID.setText("Ingrese el ID");
                tfID.setForeground(lightGray);

                //Verificar que el cliente exista y mostrar los datos en el nuevo panel
                if (impuestoResultado != null) {
                    taDescripcionResultado.setText(impuestoResultado.getDescripcion());
                    tfTasaResultado.setText(String.valueOf(impuestoResultado.getTasaImpuesto()));
                    tfFechaResultado.setText(impuestoResultado.getFecha());

                    //Cambiar de panel
                    pnlBuscar.setVisible(false);
                    pnlResultado.setVisible(true);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error en el proceso de busqueda: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe llenar al menos un campo para realizar la búsqueda", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jlBuscarMouseClicked

    private void tfIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfIDFocusGained
        // Metodo para eliminar el texto por default y cambiar a un color más oscuro. Tambien evita que el texto se borre cuando el usuario escribe
        if (tfID.getText().equals("Ingrese el ID")) {
            tfID.setText("");
            tfID.setForeground(btnBuscar.getForeground());
        }
    }//GEN-LAST:event_tfIDFocusGained

    private void tfFechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFechaFocusGained
        // Metodo para eliminar el texto por default y cambiar a un color más oscuro. Tambien evita que el texto se borre cuando el usuario escribe
        if (tfFecha.getText().equals("Ingrese la fecha de vencimiento")) {
            tfFecha.setText("");
            tfFecha.setForeground(btnBuscar.getForeground());
        }
    }//GEN-LAST:event_tfFechaFocusGained

    private void tfTasaResultadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTasaResultadoFocusGained
        //Efecto tipo placeholder para el campo Nombre
        if (tfTasaResultado.getText().equals("Ingrese la tasa del impuesto")) {
            tfTasaResultado.setText("");
            tfTasaResultado.setForeground(btnBuscar.getForeground());
        }
    }//GEN-LAST:event_tfTasaResultadoFocusGained

    private void tfFechaResultadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFechaResultadoFocusGained
        //Efecto tipo placeholder para el campo Cedula
        if (tfFecha.getText().equals("Ingrese la cédula")) {
            tfFecha.setText("");
            tfFecha.setForeground(btnBuscar.getForeground());
        }
    }//GEN-LAST:event_tfFechaResultadoFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnEditar;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JLabel h1Busqueda;
    private javax.swing.JLabel h1Registro;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jlBuscar;
    private javax.swing.JLabel jlDescripcion;
    private javax.swing.JLabel jlEditar;
    private javax.swing.JLabel jlEliminar;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlFecha1;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlTasa;
    private javax.swing.JLabel jlcharWarning;
    private javax.swing.JPanel pnlBuscar;
    private javax.swing.JPanel pnlResultado;
    private javax.swing.JTextArea taDescripcionResultado;
    private javax.swing.JTextField tfFecha;
    private javax.swing.JTextField tfFechaResultado;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfTasaResultado;
    // End of variables declaration//GEN-END:variables
}
